version: 2
updates:
  - package-ecosystem: "npm" # or "pnpm", "yarn"
    directory: "/"           # location of package.json
    schedule:
      interval: "weekly"     # options: daily, weekly, monthly
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all" # or "direct", "indirect"
