name: Changeset

on:
  pull_request:
    branches:
      - '**'

jobs:
  validate-changeset:
    name: Validate Format
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Locate Changeset Files
        id: locate_changesets
        run: |
          # Find all changeset files, excluding README.md
          changeset_files=$(find .changeset -type f -name "*.md" ! -name "README.md")

          if [ -z "$changeset_files" ]; then
            echo "No changeset files found. Skipping validation."
            exit 0 # Pass if no changesets exist
          fi

          echo "Validating changeset files..."
          ERROR_FOUND=0

          for file in $changeset_files; do
            echo "Validating file: $file"

            # Extract the first non-empty line after the YAML front matter
            first_content_line=$(awk 'BEGIN {skip=0} /^---$/ {if (skip==0) {skip=1; next} else {skip=2; next}} skip==2 && NF{print; exit}' "$file")

            # Ensure the first line starts with an alphabet character (A–Z or a–z)
            if ! [[ "$first_content_line" =~ ^[A-Za-z] ]]; then
              echo "Changeset file '$file' must start with a alphabet character."
              ERROR_FOUND=1
            fi
          done

          if [ "$ERROR_FOUND" -eq 1 ]; then
            echo "One or more changeset files are incorrectly formatted. Failing the validation."
            exit 1
          fi

      - name: Validation Success
        run: echo "All changeset files are correctly formatted."
